FROM node:18-slim

WORKDIR /usr/blog-app-api

COPY package*.json ./
COPY yarn* ./
RUN yarn install --frozen-lockfile
ENV NODE_ENV=production
COPY . .
RUN yarn run build
EXPOSE 3000


CMD [ "node", "./dist/index.js" ]